language: cpp

install:
  - curl http://ubuntu.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - echo deb http://ubuntu.openturns.org xenial main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
  - sudo apt-get -y install libopenturns-dev python3-openturns python3-dev cmake swig texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python3-matplotlib python3-pip python3-setuptools
  - sudo rm -r /opt/python/*
  - pip3 install "sphinx<3" numpydoc "matplotlib<3" "numpy<1.19" --user --upgrade

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local
    -DCMAKE_CXX_FLAGS="-Wall -Wextra"
    -DPYTHON_EXECUTABLE=/usr/bin/python3
    -DSPHINX_EXECUTABLE=~/.local/bin/sphinx-build
    .
  - make install -j2 && make tests -j2 && ctest -j2 --output-on-failure --timeout 100 

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone https://${GH_TOKEN}@github.com/openturns/openturns.github.io.git
  - PROJECT_REPONAME=`echo "${TRAVIS_REPO_SLUG}" | cut -d "/" -f 2`
  - if test -n "${TRAVIS_TAG}"; then
        TRAVIS_BRANCH=${TRAVIS_TAG:1};
    fi
  - mkdir -p openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cp -r ~/.local/share/${PROJECT_REPONAME}/doc/html/* openturns.github.io/${PROJECT_REPONAME}/${TRAVIS_BRANCH}
  - cd openturns.github.io
  - touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build ${PROJECT_REPONAME} ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1

env:
  global:
    secure: "E/JpsW8RufcemS/jKAlhphUh8IbAWfnjcAUKKmEZnrgYS32JXqsm8yeBDQhMo+TnWJxKkYKA0o49EzDUKMZHXlJtU2TB/rkuPN/QGYCOyfk4X1tm7I9hb6kmUKuWWC3POj7D1ENVsZr6dQSUzhzQ6sbDTQno5SLAAvfjDCzoii3QwTa9SRH3mV9XUCnehrB8/io+3dFvxYenNbtHOIxwZV/F6NVX6W+9HI2tl6RAzdP9GeH5s5Y6gU0AuM4hBnLQxAMF4r/RatE4/WkCDdbqULqCLfIm7TKcJaj/4euyuKRbS4PETsrhJQxHfjRFFNSmICpQd37TTSrQBGCVukWZJzz3eI/vNhFP8a1Z5HGS7OLDU2W14gp1011b9GjbuuCwe3K8OHngbgwXHmvQEHFnNHMP0zuAdZD8xk7W/N9JhUZ3bYWJE18fPj0MLumqvIA+5SS2zobuFE4yg3G3xR76uoNjeZmq0m1Nez9AEZdFoqNZbJ6BSwJpd55t+ED0pAcEbu8iKXe7W2urS/44+IWVbKxKyFvr3pu/rSoaopKCfxevFAooH+ajb+IaFUx5kAVGflahjSzlkPFY8k1misSaFiOvquEW4bZwNtAuWW5dJkO2D2lLaaLc1hNRYiMsMu2ese0+gti/qp9PMrJGozlyjMEsdCnnyz07M4nK17MHouA="

